### ISSUE TITLE
Can't import supriya

### ISSUE THREAD

**Issue by pabloriera** [josiah-wolf-oberholtzer/supriya#32]
When I do an import I have the following error

`ImportError: No module named 'abjad.tools.commandlinetools.DirectoryScript'`

I installed abjad from the git repo. What am I doing wrong?

Thanks

**Comment by josiah-wolf-oberholtzer** [comment]
Try updating your local `abjad` copy.

`abjad.tools.commandlinetools.DirectoryScript` doesn't exist anymore.

**Comment by pabloriera** [comment]
But I just clone the abjad repo...

**Comment by pabloriera** [comment]
And this line is in the supriya source

```
File "supriya/supriya/tools/scripttools/RunDoctestsScript.py", line 9, in <module>
    from abjad.tools.commandlinetools.DirectoryScript import DirectoryScrip
```

**Comment by josiah-wolf-oberholtzer** [comment]
Well, that line in `supriya` is out-of-date.

Unfortunately I haven't had time to work on this project for a few months.

Because this package is tightly coupled to Abjad, which is currently changing quite rapidly, there are probably going to be some or many bugs.

**Comment by pabloriera** [comment]
Ok, no problem, I just thought I was doing something wrong. Could I checkout to an old version of Abjad? Would you recommend a version?

Thanks

**Comment by josiah-wolf-oberholtzer** [comment]
Hold on. I will try and get it working right this moment.

**Comment by josiah-wolf-oberholtzer** [comment]
I've pushed a change up that should at least let you play around, maybe.

There are probably still going to be failing tests (both doctest and unit tests), but fewer than before.

**Comment by elib** [comment]
Hi --
This is still broken (see [this line of the supriya source](https://github.com/josiah-wolf-oberholtzer/supriya/blob/a43a711e7ba1725a015efac0412226337c3feff3/supriya/tools/scripttools/RunDoctestsScript.py#L2)). What version of abjad can we revert to so this works again?
Thanks!

**Comment by elib** [comment]
running `setup.py` actually fixed it? sorry!

**Comment by josiah-wolf-oberholtzer** [comment]
@elib Yes, as I said before those classes were renamed in Abjad recently. Installing Abjad from source will fix the errors. There are probably going to be more errors once you actually start trying to play with `supriya`. Hopefully I'll be back to developing on the project in a few weeks.

**Comment by elib** [comment]
Thanks!
It was confusing because I was using `pip` and friends and it was not working, but `setup.py` did the trick.

**Comment by josiah-wolf-oberholtzer** [comment]
Hunh. For my curiosity, do you remember what `pip` command you were trying to run that didn't work?

Normally, I run `pip install -e .` in the same directory as the `setup.py` file, and that works fine.

**Comment by elib** [comment]
I am pretty sure that's what I was doing. But I also had several issues with different versions of python and tox and all that stuff. I'm not very used to working with python .... most likely an error on my part somehow.
